{% set name = "cagecleaner" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 95bac43ac19f11008c38ea1c9477e00403fd44bf4a425ccec70426b8f25b50b9

build:
  number: 0
  entry_points:
    - cagecleaner = cagecleaner.cagecleaner:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  run_exports:
    - {{ pin_subpackage('cagecleaner', max_pin="x.x") }}

requirements:
  host:
    - python==3.12
    - pip
    - setuptools
  run:
    - python==3.12
    - biopython
    - cblaster
    - pandas
    - scipy==1.14.1
    - ncbi-datasets-cli
    - entrez-direct

test:
  commands:
    - cagecleaner -h

about:
  home: "https://github.com/LucoDevro/CAGEcleaner"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Genomic redundancy removal tool for cblaster hit sets"
  doc_url: "https://github.com/LucoDevro/CAGEcleaner/wiki"
  dev_url: "https://github.com/LucoDevro/CAGEcleaner"

extra:
  recipe-maintainers:
    - LucoDevro
  additional-platforms:
    - linux-64
    - osx-arm64
  identifiers:
    - doi:10.1101/2025.02.19.639057
